field.storage_settings.entity_reference_override:
  type: base_entity_reference_field_settings
  label: 'Entity reference override field storage settings'

field.field_settings.entity_reference_override:
  type: field.field_settings.entity_reference
  label: 'Entity reference override field settings'

field.widget.settings.entity_reference_autocomplete_with_override:
  type: field.widget.settings.entity_reference_autocomplete
  label: 'Entity reference override autocomplete display format settings'
  mapping:
    form_mode:
      type: string
      label: 'Form mode'
