field.storage_settings.entity_reference_override:
  type: base_entity_reference_field_settings
  label: 'Entity reference override field storage settings'

field.field_settings.entity_reference_override:
  type: field.field_settings.entity_reference
  label: 'Entity reference override field settings'

field.widget.settings.entity_reference_override_autocomplete:
  type: field.widget.settings.entity_reference_autocomplete
  label: 'Entity reference override autocomplete display format settings'
