field.storage_settings.entity_reference_override:
  type: base_entity_reference_field_settings
  label: 'Media settings'

field.field_settings.entity_reference_override:
  type: field.field_settings.entity_reference
  label: 'Media settings'
